# package
app_name: parametric_model

# inputs
rc_test_data_file: rc_test_data.csv
qp_region_test_data_file: qp_region_test_data.csv
qp_mp_test_data_file: qp_mp_test_data.csv
lp_region_test_data_file: lp_region_test_data.csv
lp_mp_test_data_file: lp_mp_test_data.csv
saved_model_file: mp

# this is the most important, to remove redundant rows from M if max of the row
# is smaller than this value
# Too small, not enough boundaries are removed
# Too big, too many boundaries are removed
allclose_tol: 1e-9

lp_solver_path: 'C:\\w64\glpsol'
lp_solver_setting: 'glpk'
qp_solver_path: 'C:\\cygwin64\\home\\user1\\Ipopt-3.12.12\\bin\\ipopt'
qp_solver_setting: 'ipopt'

# redundancy_checker
relax_tol: 1e-9
zero_tol: 1e-9

# generic_solver
# constraints with dual larger than this is considered active
# Too big, then active constraints are missed
# Too small, then too many active constraints 
# for LP, glpk automatically make inactive duals exactly zero
lp_activedual_tol: 1e-12
qp_activedual_tol: 1e-9

# region generator
lp_newregion_tol: 1e-6
qp_newregion_tol: 1e-6 # 1000 times the active constraint tolerance

max_iter_default: 100

verif_test_size: 10