# package
app_name: parametric_model

# inputs
rc_test_data_file: rc_test_data.csv
qp_region_test_data_file: qp_region_test_data.csv
qp_mp_test_data_file: qp_mp_test_data.csv
lp_region_test_data_file: lp_region_test_data.csv
lp_mp_test_data_file: lp_mp_test_data.csv
saved_model_file: mp

# rows from M are considered redundant if max in row is smaller than this value
allclose_tol: 1e-9

# lp_solver_path: 'C:\\w64\glpsol'
# lp_solver_setting: 'glpk'
# qp_solver_path: 'C:\\cygwin64\\home\\user1\\Ipopt-3.12.12\\bin\\ipopt'
# qp_solver_setting: 'ipopt'
lp_solver_setting: cplex
qp_solver_setting: cplex

# redundancy_checker
relax_tol: 1e-9
zero_tol: 1e-9

# generic_solver
# constraints with dual larger than this is considered active
lp_activedual_tol: 1e-12
qp_activedual_tol: 1e-12

# region generator
# shift boundary a little when creating a new region to prevent overlaps
# due to 
lp_newregion_tol: 1e-12
qp_newregion_tol: 1e-12 

max_iter_default: 100

verif_test_size: 10