# package
app_name: parametric_model

# inputs
rc_test_data_file: rc_test_data.csv

allclose_tol: 1e-6

# solver_path = 'C:\\w64\\glpsol'
solver: 'cplex'

# redundancy_checker
relax_tol: 1e-6
zero_tol: 1e-6


