# package
app_name: parametric_model

# inputs
rc_test_data_file: rc_test_data.csv
# this is the most important, to remove redundant rows from M if max of the row
# is smaller than this value
# Too small, not enough boundaries are removed
# Too big, too many boundaries are removed
allclose_tol: 1e-10

# solver_path: 'C:\\w64\glpsol'
# solver_setting: 'glpk'
solver_path: 'C:\\cygwin64\\home\\user1\\Ipopt-3.12.12\\bin\\ipopt'
solver_setting: 'ipopt'

# redundancy_checker
relax_tol: 1e-6
zero_tol: 1e-6

# quadratic_solver. Constraint with slack smaller than this is considered active
# Too small, then active constraints are missed
# Too big, then too many active constraints 
feas_tol: 1e-2

